journal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('journals.urls')),
]

journals/urls.py
"""journals URL patterns"""

from django.urls import path
from . import views

app_name = 'journals'
urlpatterns = [
    #Home page
    path('', views.index, name='index'),
    #Topics page
    path('topics/', views.topics, name='topics'),
    #Single topic page
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    #Adding new topic page
    path('new_topic/', views.new_topic, name='new_topic'),
    #New entry page
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    #Editting entry page
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
]

users/urls.py
"""URL patterns for users"""

from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
    #Include default auth urls
    path('', include('django.contrib.auth.urls')),
    #Registration page
    path('register/', views.register, name='register'),
]

journals/models.py
from django.db import models
from django.contrib.auth.models import User

class Topic(models.Model):
    """A Topic the user chose"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """Return a string representation"""
        return self.text


class Entry(models.Model):
    """Entries for specific topics"""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """Return a string representation"""
        if len(self.text) <= 50:
            return self.text
        else:
            return f"{self.text[:50]}..."

users/models.py
from django.db import models

# Create your models here.

journals/forms.py
from django import forms
from django import forms
from .models import Entry, Topic

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text' : ''}
        
class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text' : ''}
        widgets = {'text' : forms.Textarea(attrs={'cols':80})}
        

journals/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import Http404
from .models import Topic, Entry
from .forms import TopicForm, EntryForm

def index(request):
    """The home page for Journal"""
    return render(request, 'journals/index.html')

@login_required
def topics(request):
    """Show all topics"""
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics' : topics}
    return render(request, 'journals/topics.html', context)

@login_required
def topic(request, topic_id):
    """Show single topic identified by id"""
    topic = get_object_or_404(Topic, id=topic_id)
    check_topic_owner(request, topic)
    entries = topic.entry_set.order_by('-date_added') # - for reverse order
    context = {'topic' : topic, 'entries' : entries}
    return render(request, 'journals/topic.html', context)
    
@login_required
def new_topic(request):
    """Adding a new topic"""
    if request.method != 'POST':
        form = TopicForm() #No data, create blank form
    else:
        form = TopicForm(data=request.POST) #POST data, process it
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return redirect('journals:topics')

    #Show blank or invalid
    context = {'form' : form}
    return render(request, 'journals/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
    """New entry for particular topic"""
    topic = Topic.objects.get(id=topic_id)
    check_topic_owner(request, topic)

    if request.method != 'POST':
        form = EntryForm() #No data, blank form
    else:
        form = EntryForm(data=request.POST) #POST data from the request object
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('journals:topic', topic_id=topic_id)

    #Blank or invalid form
    context = {'topic':topic, 'form':form}
    return render(request, 'journals/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    """Editting entry"""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    check_topic_owner(request, topic)
    

    if request.method != 'POST':
        form = EntryForm(instance=entry) #Fill form with current entry
    else:
        form =EntryForm(instance=entry, data=request.POST) # data so process
        if form.is_valid():
            form.save()
            return redirect('journals:topic', topic_id=topic.id)

    context = {'entry':entry, 'topic':topic, 'form':form}
    return render(request, 'journals/edit_entry.html', context)

def check_topic_owner(request, topic): #Makes sure the topic belongs to the user
    if topic.owner != request.user:
        raise Http404

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

def register(request):
    """Register new"""
    if request.method != 'POST':
        form = UserCreationForm() #Blank form
    else:
        form = UserCreationForm(data=request.POST) #Completed form
        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            return redirect('journals:index')

    #Blank or invalid
    context = {'form':form}
    return render(request, 'registration/register.html', context)

journals/templates/journals/base.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Journal</title>

  {% load bootstrap5 %}
  {% bootstrap_css %}
  {% bootstrap_javascript %}

</head>
<body>
  <nav class="navbar navbar-expand-md navbar-dark bg-primary mb-4 border">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'journals:index' %}">  Journal</a>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
        data-bs-target="#navbarCollapse" aria-controls="navbarCollapse"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'journals:topics' %}">
              Topics</a></li>
        </ul> <!-- End of links on left side of navbar -->

        <!-- users-related links -->
        <ul class="navbar-nav ms-auto mb-2 mb-md-0">

          {% if user.is_authenticated %}
            <li class="nav-item">
              <span class="navbar-text me-2">Hello, {{ user.username }}.
                </span></li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'users:register' %}">
                  Register</a></li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'users:login' %}">
                  Log in</a></li>
          {% endif %}

        </ul> <!-- End of users-related links -->

        {% if user.is_authenticated %}
          <form action="{% url 'users:logout' %}" method='post'>
            {% csrf_token %}
            <button name='submit' class='btn btn-outline-light btn-sm'>
              Log out</button>
          </form>
        {% endif %}

      </div> <!-- Closes collapsible parts of navbar -->

    </div> <!-- Closes navbar's container -->
  </nav> <!-- End of navbar -->

  <main class="container">
    <div class="pb-2 mb-2 border-bottom">
      {% block page_header %}{% endblock page_header %}
    </div>

    <div>
      {% block content %}{% endblock content %}
    </div>
  </main>

</body>
</html>

journals/templates/journals/edit_entry.html
{% extends "journals/base.html" %}
{% load bootstrap5 %}

{% block page_header %}
  <h1>Add a new topic</h1>
  <a class="btn btn-primary mt-2 mb-2"
          href="{% url 'journals:topic' topic.id %}">Topic &raquo;</a>
{% endblock page_header %}

{% block content %}  

  <form action="{% url 'journals:edit_entry' entry.id %}" method='post' class="form">
    {% csrf_token %}  
    {% bootstrap_form form %}
    {% buttons %}
      <button name="submit" class="btn btn-primary">Save changes</button>
    {% endbuttons %}
  </form>

{% endblock content %}

journals/templates/journals/index.html
{% extends "journals/base.html" %}

{% block page_header %}
  <div class="p-3 mb-4 bg-light border rounded-3">
    <div class="container-fluid py-4">
      <h1 class="display-3">Journal helps you to keep track of any topic you choose, eg. training, diet, learning or just daily thoughts.</h1>
      
      <p class="lead">Make your own Journal, and keep a list of the
      topics you want. Whenever you get an idea or learn something new
      about a topic, make an entry summarizing your thoughts or what you've learned. Or for example keep track of your training or diet.</p>
      
      {% if user.is_authenticated %}
      <a class="btn btn-primary btn-lg mt-1"
          href="{% url 'journals:topics' %}">Topics &raquo;</a>
      {% else %}
      <a class="btn btn-primary btn-lg mt-1"
          href="{% url 'users:register' %}">Register &raquo;</a>
      <a class="btn btn-primary btn-lg mt-1"
          href="{% url 'users:login' %}">Log in &raquo;</a>
      {% endif %}
    </div>
  </div>
{% endblock page_header %}

journals/templates/journals/new_entry.html
{% extends "journals/base.html" %}
{% load bootstrap5 %}

{% block page_header %}
  <h1>Add a new entry</h1>
  <a class="btn btn-primary mt-2 mb-2"
          href="{% url 'journals:topic' topic.id %}">Topic &raquo;</a>
{% endblock page_header %}

{% block content %}  

  <form action="{% url 'journals:new_entry' topic.id %}" method='post' class="form">
    {% csrf_token %}  
    {% bootstrap_form form %}
    {% buttons %}
      <button name="submit" class="btn btn-primary">Add entry</button>
    {% endbuttons %}
  </form>

{% endblock content %}

journals/templates/journals/new_topic.html
{% extends "journals/base.html" %}
{% load bootstrap5 %}

{% block page_header %}
  <h1>Add a new topic</h1>
  <a class="btn btn-primary mt-2 mb-2"
          href="{% url 'journals:topics' %}">Topics &raquo;</a>
{% endblock page_header %}

{% block content %}  

  <form action="{% url 'journals:new_topic' %}" method='post' class="form">
    {% csrf_token %}  
    {% bootstrap_form form %}
    {% buttons %}
      <button name="submit" class="btn btn-primary">Add topic</button>
    {% endbuttons %}
  </form>

{% endblock content %}

journals/templates/journals/topic.html
{% extends "journals/base.html" %}
{% load bootstrap5 %}

{% block page_header %}
  <h1>{{ topic.text }}</h1>
  <a class="btn btn-primary mt-2 mb-2"
          href="{% url 'journals:topics' %}">Topics &raquo;</a>
{% endblock page_header %}


{% block content %}

  <a class="btn btn-primary mt-2 mb-2"
          href="{% url 'journals:new_entry' topic.id %}">Add a new_entry &raquo;</a>
  <p></p>        
  <ul>
    {% for entry in entries %}
    <div class="card mb-3">
      <!-- Card header with timestamp and edit link -->
      <h4 class="card-header">
        {{ entry.date_added|date:'M d, Y H:i' }}
        <small><a href="{% url 'journals:edit_entry' entry.id %}">
          edit entry</a></small>
      </h4>
      <!-- Card body with entry text -->
      <div class="card-body">{{ entry.text|linebreaks }}</div>
    </div>
   
    {% empty %}
      <li>There are no entries for this topic yet.</li>
    {% endfor %}
  </ul> 

{% endblock content %}

journals/templates/journals/topics.html
{% extends "journals/base.html" %}

{% block page_header %}
  <h1>Topics</h1>
{% endblock page_header %}


{% block content %}

<ul class="list-group border-bottom pb-2 mb-4">
    {% for topic in topics %}
    <li class="list-group-item border-0"><h3>
        <a href="{% url 'journals:topic' topic.id %}">{{ topic }}</a>
      </h3></li>
    {% empty %}
    <li class="list-group-item border-0">No topics have been added yet.</li>
    {% endfor %}
  </ul>
  <a class="btn btn-primary mt-2"
          href="{% url 'journals:new_topic' %}">Add a new topic &raquo;</a>
  

{% endblock content %}